version: "3"

services:
  postgres:
    image: postgres:15-alpine
    container_name: spindox-events-postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
